set_property IOSTANDARD LVCMOS33 [get_ports{CS[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports{CS[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports{CS[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports{CS[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports{sig_seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports{sig_seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports{sig_seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports{sig_seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports{sig_seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports{sig_seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports{sig_seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports{sig_seg[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports{clk}]
set_property IOSTANDARD LVCMOS33 [get_ports{pause_key}]
set_property IOSTANDARD LVCMOS33 [get_ports{reset_key}]
set_property IOSTANDARD LVCMOS33 [get_ports{start_key}]

set_property IOSTANDARD LVCMOS33 [get_ports light]
set_property IOSTANDARD LVCMOS33 [get_ports alert]

set_property PACKAGE_PIN D5 [get_ports {sig_seg[0]}]
set_property PACKAGE_PIN B4 [get_ports {sig_seg[1]}]
set_property PACKAGE_PIN A4 [get_ports {sig_seg[2]}]
set_property PACKAGE_PIN A3 [get_ports {sig_seg[3]}]
set_property PACKAGE_PIN B1 [get_ports {sig_seg[4]}]
set_property PACKAGE_PIN A1 [get_ports {sig_seg[5]}]
set_property PACKAGE_PIN B3 [get_ports {sig_seg[6]}]
set_property PACKAGE_PIN B2 [get_ports {sig_seg[7]}]

set_property PACKAGE_PIN H1 [get_ports {CS[3]}]
set_property PACKAGE_PIN C1 [get_ports {CS[2]}]
set_property PACKAGE_PIN C2 [get_ports {CS[1]}]
set_property PACKAGE_PIN G2 [get_ports {CS[0]}]

set_property PACKAGE_PIN T5 [get_ports clk]
set_property PACKAGE_PIN R15 [get_ports pause_key]
set_property PACKAGE_PIN P15 [get_ports reset_key]
set_property PACKAGE_PIN R17 [get_ports start_key]

set_property PACKAGE_PIN K2 [get_ports light]
set_property PACKAGE_PIN G13 [get_ports alert]

set_property IOSTANDARD LVCMOS33 [get_ports {CS[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CS[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CS[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CS[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sig_seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sig_seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sig_seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sig_seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sig_seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sig_seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sig_seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sig_seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports pause_key]
set_property IOSTANDARD LVCMOS33 [get_ports reset_key]
set_property IOSTANDARD LVCMOS33 [get_ports start_key]
